import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import { useStore } from "@/contexts";
import { DispatchType } from "@/enums";
import { getExample } from "@/services/example"
import { useHttpRequest } from "@/hooks";
import { useForm } from "react-hook-form";

const param = {}

export default function Home() {
  const [count, setCount] = useState(0)
  const { state, getters, dispatch } = useStore();
  const { data } = useHttpRequest(getExample, param)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        {data && data.map((m) => <span key={m.id}>{m.name}</span>)}
        <button
          className={'bg-red-500'}
          onClick={() => {
            dispatch(DispatchType.SET_EXAMPLE_COLLECTION, { id: getters.example.exampleList.length + 1 });
          }}
        >
          ADD
        </button>
        <button
          className={'bg-blue-500'}
          onClick={() => setCount(count + 1)}
        >
          Count = {count}
        </button>

        {getters.example.exampleList.map((example) => (
          <div key={example.id}>{example.id}</div>
        ))}
        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
